version: '3.7'

services:
  cicd_orchestrator:
    container_name: gio_cicd_orchestrator
    # image: quay.io/gravitee-lab/pull-request-bot:${DOCKER_TAG} stable-latest
    image: quay.io/gravitee-lab/cicd-orchestrator:stable-latest
    environment:
      - MONGO_INITDB_DATABASE=gravitee
    # env_file:
      # - .compose.env # atually no, same [.env] file ... ?
    env_file:
      - .compose.env
    entrypoint: /bin/sh
    stdin_open: true
    tty: true
    volumes:
      # [$PWD/gravitee/cicd/pipeline]: is in the .gitignore to allow local tests
      - $PWD/graviteeio/cicd/pipeline:/graviteeio/cicd/pipeline
      - $PWD/.env:/graviteeio/cicd/.env
      - $PWD/.secrets.json:/graviteeio/cicd/.secrets.json
