version: 2.1
description: |
    Sample orb description
display:
    home_url: https://www.website.com/docs
    source_url: https://www.github.com/EXAMPLE_ORG/EXAMPLE_PROJECT
commands:
    greet:
        description: |
            This command is a demo use of Orbs command parameters. This command echoes a greeting message, using Orbs file inclusion. It uses : * the `greet_to` Orb command parameter, to set the names of the new team members to welcome. * the `greet_team` Orb command parameter, to set the name of the team the welcomed team members will be in.
        parameters:
            greet_team:
                default: salesforce
                description: Greeting in which Team?
                enum:
                    - development
                    - support
                    - devops
                    - salesforce
                type: enum
            greet_to:
                default: World of Orbs
                description: Hello to whom?
                type: string
        steps:
            - run:
                command: |4

                    export PARAM_TO=${PARAM_TO:-"this is the default value of the 'PARAM_TO' env. var., defined in the [$0] script."}
                    export PARAM_TEAM=${PARAM_TEAM:-"this is the default value of the 'PARAM_TEAM' env. var., defined in the [$0] script."}


                    Greet() {
                        echo "Hello ${PARAM_TO} ! :)"
                        echo "Welcome to the ${PARAM_TEAM} Team! "
                    }

                    # Will not run if sourced for bats-core tests.
                    # View src/tests for more information.
                    ORB_TEST_ENV="bats-core"
                    if [ "${0#*$ORB_TEST_ENV}" == "$0" ]; then
                        Greet
                    fi
                environment:
                    PARAM_TEAM: <<parameters.greet_team>>
                    PARAM_TO: <<parameters.greet_to>>
                name: Hello Greeting
executors:
    default:
        description: |
            This is a sample executor using Docker and Node.
        docker:
            - image: cimg/node:<<parameters.tag>>
        parameters:
            tag:
                default: lts
                description: |
                    Pick a specific circleci/node image variant: https://hub.docker.com/r/cimg/node/tags
                type: string
jobs:
    hello-job:
        description: |
            Sample description
        executor: default
        parameters:
            greet_team:
                default: development
                description: Greeting in which Team? (hello job)
                enum:
                    - development
                    - support
                    - devops
                    - salesforce
                type: enum
            greet_to:
                default: Titouan, David, Nicolas, Azize
                description: Hello to whom? (job)
                type: string
        steps:
            - greet:
                greet_team: << parameters.greet_team>>
                greet_to: << parameters.greet_to>>
    nodejs-job:
        description: |
            Sample description
        executor: default
        parameters:
            greet_team:
                default: development
                description: Greeting in which Team? (hello job)
                enum:
                    - development
                    - support
                    - devops
                    - salesforce
                type: enum
            greet_to:
                default: Titouan, David, Nicolas, Azize
                description: Hello to whom? (job)
                type: string
        steps:
            - greet:
                greet_team: << parameters.greet_team>>
                greet_to: << parameters.greet_to>>
            - checkout
            - run:
                command: npm ci
                name: install
            - run:
                command: npm run validate
                name: validate
            - run:
                command: echo installing semantic-release && npx -p semantic-release@15 -c 'echo running semantic-release && semantic-release'
                name: release
examples:
    example-template:
        description: |
            Sample example description.
        usage:
            version: "2.1"
            orbs:
                <orb-name>: <namespace>/<orb-name>@1.2.3
            workflows:
                use-my-orb:
                    jobs:
                        - <orb-name>/<job-name>
    full-example:
        description: |
            This Full example demonstrates how to use : * The "`hello-job`" and "`nodejs-job`" `Orb` job, * along with an "oldschool"-defined job, invoked via the "`wflow_with_old_sch00l_job`" workflow
            The "oldschool"-defined job example demonstrates how to use the "`greet`" `Orb` command, and especially how to pass a value at runtime, to the `greet` `Orb` command, using `Orb` parameters : * The first `greet` command call, will welcome "Gravitee Mates" in the default Team * The second `greet` command call, will welcome "Paul", "Marc", and "Jean" in the "devops" Team * The Third `greet` command call, will welcome "Alexandre", "Yann", and "Laurie" in the "development" Team
        usage:
            version: "2.1"
            orbs:
                gravit33io-devorbs: orbinoid2/gravitee-dev-repos@0.0.5
            jobs:
                oldschool:
                    docker:
                        - image: circleci/node:latest
                    steps:
                        - checkout
                        - gravit33io-devorbs/greet:
                            greet_to: Gravitee Mates
                        - gravit33io-devorbs/greet:
                            greet_team: devops
                            greet_to: Paul, Marc, Jean
                        - gravit33io-devorbs/greet:
                            greet_team: development
                            greet_to: Alexandre, Yann, Laurie
                        - run:
                            command: npm ci
                            name: install
                        - run:
                            command: npm run validate
                            name: validate
                        - run:
                            command: echo installing semantic-release && npx -p semantic-release@15 -c 'echo running semantic-release && semantic-release'
                            name: release
            workflows:
                hell0_n0dejs_wfl0w:
                    jobs:
                        - gravit33io-devorbs/nodejs-job:
                            context: cicd-orchestrator
                            greet_team: salesforce
                            greet_to: Titouan, Paul, Nicolas, Azize, David, Florent, Laurie, Rory
                hell0_workfl0w:
                    jobs:
                        - gravit33io-devorbs/hello-job:
                            context: yourcontext
                            greet_team: salesforce
                            greet_to: Titouan, Paul, Nicolas, Azize, David, Florent, Laurie, Rory
                version: 2.1
                wflow_with_old_sch00l_job:
                    jobs:
                        - oldschool:
                            context: cicd-orchestrator
    greet-command-example:
        description: |
            This example demonstrates how to use the "`greet`" `Orb` command, and especially how to pass a value at runtime, to the `greet` `Orb` command, using `Orb` parameters : * The first `greet` command call, will welcome "Paul", "Marc", and "Jean" in the "devops" Team * The second `greet` command call, will welcome "Alexandre", "Yann", and "Laurie" in the "development" Team
        usage:
            version: "2.1"
            orbs:
                gravit33io-devorbs: orbinoid2/gravitee-dev-repos@0.0.5
            jobs:
                build:
                    docker:
                        - image: circleci/node:latest
                    steps:
                        - checkout
                        - gravit33io-devorbs/greet:
                            greet_team: devops
                            greet_to: Paul, Marc, Jean
                        - gravit33io-devorbs/greet:
                            greet_team: development
                            greet_to: Alexandre, Yann, Laurie
            workflows: null
    nodejs-job-example:
        description: |
            This example demonstrates how to use the "`hello-job`" `Orb` job, along with an "oldschool"-defined job
            The "oldschool"-defined job example demonstrates how to use the "`greet`" `Orb` command, and especially how to pass a value at runtime, to the `greet` `Orb` command, using `Orb` parameters : * The first `greet` command call, will welcome "Gravitee Mates" in the default Team * The second `greet` command call, will welcome "Paul", "Marc", and "Jean" in the "devops" Team * The Third `greet` command call, will welcome "Alexandre", "Yann", and "Laurie" in the "development" Team
        usage:
            version: "2.1"
            orbs:
                gravit33io-devorbs: orbinoid2/gravitee-dev-repos@0.0.5
            workflows:
                hell0_n0dejs_wfl0w:
                    jobs:
                        - gravit33io-devorbs/nodejs-job:
                            context: cicd-orchestrator
                            greet_team: salesforce
                            greet_to: Titouan, Paul, Nicolas, Azize, David, Florent, Laurie, Rory
                version: 2.1

