# Circle CI Pipeline for an Orb Project
version: 2.1
orbs:
  secrethub: secrethub/cli@1.0.0
jobs:
  build:
    machine:
      image: 'ubuntu-1604:201903-01'    # recommended linux image - includes Ubuntu 16.04, docker 18.09.3, docker-compose 1.23.1
      # resource_class: medium
      # docker_layer_caching: true    # default - false # requires a Circle CI plan that includes [Docker layer caching feature]
    # environment:
      # ANY_VARIABLE_SOMEDAY: <value here>
    steps:
      - checkout
      - secrethub/install
      - run:
          name: "Testing local docker installation"
          command: docker version
